"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api/client";
import type { AdminCategoryPublic, DailyActivityValuePublic, DailyCardPublic, HistoricalCardCorrectionResult, HistoricalCategoryCorrectionResult, HistoricalCategoryHistoryPublic, UserPublic } from "@/lib/api/types";
import { Button } from "@/components/ui/button";
import { Card, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { MutationFeedback } from "@/components/admin/mutation-feedback";

interface FieldDraft { isFilled: boolean; numeric: string; time: string; boolean: boolean | null; text: string }
function draftFor(value: DailyActivityValuePublic): FieldDraft { return { isFilled: value.is_filled, numeric: value.is_filled ? value.numeric_value : "", time: value.is_filled ? (value.time_value ?? "") : "", boolean: value.is_filled ? value.boolean_value : null, text: value.is_filled ? (value.text_value ?? "") : "" }; }
function payloadFor(value: DailyActivityValuePublic, draft: FieldDraft) {
  if (!draft.isFilled) return { field_id: value.field_id, is_filled: false };
  if (["NUMBER", "COUNT", "DURATION"].includes(value.input_type)) return { field_id: value.field_id, is_filled: true, numeric_value: draft.numeric };
  if (value.input_type === "TIME") return { field_id: value.field_id, is_filled: true, time_value: draft.time };
  if (value.input_type === "BOOLEAN") return { field_id: value.field_id, is_filled: true, boolean_value: draft.boolean };
  return { field_id: value.field_id, is_filled: true, text_value: draft.text };
}

function CorrectionField({ value, draft, onChange }: { value: DailyActivityValuePublic; draft: FieldDraft; onChange: (next: FieldDraft) => void }) {
  const filledControl = value.input_type === "BOOLEAN" ? null : <label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={draft.isFilled} onChange={(e) => onChange({ ...draft, isFilled: e.target.checked })} /> Filled</label>;
  return <div className="rounded-lg border border-slate-200 bg-slate-50 p-3"><div className="mb-2 flex items-center justify-between gap-2"><div><p className="text-sm font-semibold">{value.label}</p><p className="text-xs text-slate-500">{value.input_type}{value.unit_code ? ` · ${value.unit_code}` : ""}</p></div>{filledControl}</div>{value.input_type === "BOOLEAN" ? <Select value={!draft.isFilled ? "NA" : draft.boolean === true ? "YES" : "NO"} onChange={(e) => onChange(e.target.value === "NA" ? { ...draft, isFilled: false, boolean: null } : { ...draft, isFilled: true, boolean: e.target.value === "YES" })}><option value="NA">N/A</option><option value="YES">Yes</option><option value="NO">No</option></Select> : ["NUMBER", "COUNT", "DURATION"].includes(value.input_type) ? <Input disabled={!draft.isFilled} type="number" step={value.input_type === "COUNT" ? 1 : "any"} value={draft.numeric} onChange={(e) => onChange({ ...draft, numeric: e.target.value })} /> : value.input_type === "TIME" ? <Input disabled={!draft.isFilled} type="time" value={draft.time} onChange={(e) => onChange({ ...draft, time: e.target.value })} /> : <Input disabled={!draft.isFilled} value={draft.text} onChange={(e) => onChange({ ...draft, text: e.target.value })} />}</div>;
}

export function CorrectionWorkbench({ devotees, categories, initialUserId = "" }: { devotees: UserPublic[]; categories: AdminCategoryPublic[]; initialUserId?: string }) {
  const [userId, setUserId] = useState(initialUserId);
  const [history, setHistory] = useState<HistoricalCategoryHistoryPublic | null>(null);
  const [cardDate, setCardDate] = useState(""); const [card, setCard] = useState<DailyCardPublic | null>(null);
  const [drafts, setDrafts] = useState<Record<string, FieldDraft>>({}); const [dirty, setDirty] = useState<Set<string>>(new Set());
  const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const selected = devotees.find((d) => d.id === userId) ?? null;
  const cardActivities = useMemo(() => card?.activities.filter((a) => !a.is_system_derived && a.values.length > 0) ?? [], [card]);

  useEffect(() => { setHistory(null); setCard(null); setDirty(new Set()); setError(null); setSuccess(null); }, [userId]);

  async function loadHistory() { if (!userId) return; setBusy(true); setError(null); try { setHistory(await apiFetch<HistoricalCategoryHistoryPublic>(`/api/backend/admin/corrections/devotees/${userId}/category-history`)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load category history."); } finally { setBusy(false); } }
  async function loadCard() { if (!userId || !cardDate) return; setBusy(true); setError(null); try { const loaded = await apiFetch<DailyCardPublic>(`/api/backend/admin/corrections/devotees/${userId}/cards/${cardDate}`); setCard(loaded); const next: Record<string, FieldDraft> = {}; for (const a of loaded.activities) for (const v of a.values) next[v.field_id] = draftFor(v); setDrafts(next); setDirty(new Set()); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load historical card."); } finally { setBusy(false); } }

  async function correctCategory(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!userId) return; const fd = new FormData(e.currentTarget); setBusy(true); setError(null); setSuccess(null); try { const result = await apiFetch<HistoricalCategoryCorrectionResult>(`/api/backend/admin/corrections/devotees/${userId}/category`, { method: "PATCH", body: JSON.stringify({ effective_from_week: String(fd.get("effective_from_week")), target_category_code: String(fd.get("target_category_code")), reason: String(fd.get("reason")) }) }); setSuccess(`Category corrected from ${result.effective_from_week}; ${result.affected_daily_cards} daily card(s) and ${result.affected_weekly_evaluations} weekly evaluation(s) affected.`); await loadHistory(); } catch (e2) { setError(e2 instanceof Error ? e2.message : "Historical category correction failed."); } finally { setBusy(false); } }

  async function correctCard(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!userId || !card) return; const fd = new FormData(e.currentTarget); const activities = cardActivities.map((a) => ({ activity_id: a.activity_id, values: a.values.filter((v) => dirty.has(v.field_id)).map((v) => payloadFor(v, drafts[v.field_id])) })).filter((a) => a.values.length > 0); if (!activities.length) { setError("Change at least one raw value before saving a historical correction."); return; } setBusy(true); setError(null); setSuccess(null); try { const result = await apiFetch<HistoricalCardCorrectionResult>(`/api/backend/admin/corrections/devotees/${userId}/cards/${card.card_date}`, { method: "PATCH", body: JSON.stringify({ reason: String(fd.get("reason")), activities }) }); setSuccess(`Historical card revision saved${result.weekly_evaluation_recalculated ? " and affected weekly evaluation recalculated" : ""}.`); setCard(result.card); const next: Record<string, FieldDraft> = {}; for (const a of result.card.activities) for (const v of a.values) next[v.field_id] = draftFor(v); setDrafts(next); setDirty(new Set()); } catch (e2) { setError(e2 instanceof Error ? e2.message : "Historical card correction failed."); } finally { setBusy(false); } }

  return <div className="space-y-6"><MutationFeedback error={error} success={success} /><Card><CardHeader title="Select devotee" description="Corrections are exceptional Admin actions, require reasons and are audited by the backend." /><div className="p-5"><Select value={userId} onChange={(e) => setUserId(e.target.value)}><option value="">Select devotee</option>{devotees.map((u) => <option key={u.id} value={u.id}>{u.full_name} · {u.email}</option>)}</Select>{selected ? <p className="mt-2 text-sm text-slate-500">Current: {selected.devotee_profile?.current_category.display_name ?? "—"} · {selected.account_status}</p> : null}</div></Card>
    {userId ? <><Card><CardHeader title="Historical category correction — Policy B" description="The corrected category continues from the selected week until the next actual different transition." /><div className="space-y-4 p-5"><Button type="button" variant="secondary" disabled={busy} onClick={() => void loadHistory()}>Load category history</Button>{history ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-slate-500"><tr><th className="py-2">Effective week</th><th>From</th><th>To</th><th>Source</th><th>Reason</th></tr></thead><tbody>{history.history.map((h) => <tr key={h.id} className="border-t"><td className="py-2">{h.effective_from_week}</td><td>{h.previous_category_code ?? "—"}</td><td className="font-semibold">{h.new_category_code}</td><td>{h.change_source}</td><td>{h.reason}</td></tr>)}</tbody></table></div> : null}<form onSubmit={correctCategory} className="grid gap-3 md:grid-cols-3"><label className="text-sm font-medium">Effective week<Input name="effective_from_week" type="date" required className="mt-1" /></label><label className="text-sm font-medium">Correct category<Select name="target_category_code" required className="mt-1" defaultValue=""><option value="" disabled>Select category</option>{categories.filter(c => c.is_active && !c.is_archived).map(c => <option key={c.id} value={c.code}>{c.display_name}</option>)}</Select></label><label className="text-sm font-medium md:col-span-3">Mandatory reason<Textarea name="reason" minLength={3} required className="mt-1" /></label><div className="md:col-span-3"><Button disabled={busy}>Apply Policy-B correction</Button></div></form></div></Card>
    <Card><CardHeader title="Finalized Daily Card correction" description="Correct raw facts only. Filling Sadhana Card remains system-derived and cannot be overwritten." /><div className="space-y-4 p-5"><div className="flex flex-wrap gap-2"><Input className="max-w-56" type="date" value={cardDate} onChange={(e) => setCardDate(e.target.value)} /><Button type="button" variant="secondary" disabled={!cardDate || busy} onClick={() => void loadCard()}>Load finalized card</Button></div>{card ? <form onSubmit={correctCard} className="space-y-5"><div className="rounded-lg bg-slate-50 p-3 text-sm">{card.card_date} · {card.category_name} · {card.status} · revision {card.revision_number}</div>{cardActivities.map((a) => <div key={a.entry_id} className="space-y-3"><h3 className="font-semibold">{a.name}</h3><div className="grid gap-3 md:grid-cols-2">{a.values.map((v) => <CorrectionField key={v.field_id} value={v} draft={drafts[v.field_id]} onChange={(next) => { setDrafts((old) => ({ ...old, [v.field_id]: next })); setDirty((old) => new Set(old).add(v.field_id)); }} />)}</div></div>)}<label className="block text-sm font-medium">Mandatory correction reason<Textarea name="reason" minLength={3} required className="mt-1" /></label><Button disabled={busy || dirty.size === 0}>Save historical correction</Button></form> : null}</div></Card></> : null}
    <Card className="p-5 text-sm text-slate-600"><strong>Audit note:</strong> correction/account/configuration mutations are recorded in the backend audit log. Stable backend v0.11.2 intentionally has no general audit-log listing API, so this frontend does not invent an unsupported audit endpoint.</Card>
  </div>;
}
