"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { apiFetch } from "@/lib/api/client";
import type { ActivityPublic, RuleType, ScoringRulePublic, ScoringRuleVersionPublic } from "@/lib/api/types";
import { Button } from "@/components/ui/button";
import { Card, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { MutationFeedback } from "@/components/admin/mutation-feedback";

const ruleTypes: RuleType[] = ["BOOLEAN", "THRESHOLD", "PERCENTAGE", "SYSTEM_DERIVED", "NO_SCORE"];

function pretty(value: Record<string, unknown>): string { return JSON.stringify(value, null, 2); }
function parseObject(text: string): Record<string, unknown> { const parsed: unknown = JSON.parse(text); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("Configuration must be a JSON object."); return parsed as Record<string, unknown>; }

export function ScoringRuleManager({ rules, activities, versionsByRule }: { rules: ScoringRulePublic[]; activities: ActivityPublic[]; versionsByRule: Record<string, ScoringRuleVersionPublic[]> }) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  async function mutate<T>(key: string, url: string, method: string, body: unknown, message: string) { setBusy(key); setError(null); setSuccess(null); try { await apiFetch<T>(url, { method, body: JSON.stringify(body) }); setSuccess(message); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Rule change failed."); } finally { setBusy(null); } }
  async function createRule(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const fd = new FormData(e.currentTarget); await mutate<ScoringRulePublic>("create-rule", "/api/backend/admin/config/scoring-rules", "POST", { activity_id: String(fd.get("activity_id")), name: String(fd.get("name")), rule_type: String(fd.get("rule_type")) }, "Scoring rule created."); }
  async function saveVersion(e: FormEvent<HTMLFormElement>, rule: ScoringRulePublic, pending: ScoringRuleVersionPublic | null) { e.preventDefault(); const fd = new FormData(e.currentTarget); try { const configuration = parseObject(String(fd.get("configuration") ?? "{}")); const body = { effective_from_week: String(fd.get("effective_from_week") ?? "") || null, max_score: Number(fd.get("max_score")), rounding_mode: "HALF_UP", configuration }; await mutate<ScoringRuleVersionPublic>(`version-${rule.id}`, pending ? `/api/backend/admin/config/scoring-rule-versions/${pending.id}` : `/api/backend/admin/config/scoring-rules/${rule.id}/versions`, pending ? "PATCH" : "POST", body, pending ? "Pending rule version updated." : "Pending rule version created."); } catch (e2) { setError(e2 instanceof Error ? e2.message : "Invalid JSON configuration."); } }
  return <div className="space-y-6"><MutationFeedback error={error} success={success} />
    <Card><CardHeader title="Create scoring rule" description="Create the rule identity first; executable logic lives in versioned JSON validated by FastAPI." /><form onSubmit={createRule} className="grid gap-4 p-5 md:grid-cols-3"><label className="text-sm font-medium">Activity<Select name="activity_id" required className="mt-1" defaultValue=""><option value="" disabled>Select activity</option>{activities.filter(a => !a.is_archived).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</Select></label><label className="text-sm font-medium">Rule name<Input name="name" required minLength={2} className="mt-1" /></label><label className="text-sm font-medium">Rule type<Select name="rule_type" className="mt-1">{ruleTypes.map(t => <option key={t}>{t}</option>)}</Select></label><div className="md:col-span-3"><Button disabled={busy === "create-rule"}>Create rule</Button></div></form></Card>
    <div className="space-y-5">{rules.map(rule => { const versions = versionsByRule[rule.id] ?? []; const pending = versions.find(v => v.status === "PENDING") ?? null; const reference = pending ?? versions.find(v => v.status === "ACTIVE") ?? versions[0] ?? null; const activity = activities.find(a => a.id === rule.activity_id); return <Card key={rule.id}><CardHeader title={rule.name} description={`${activity?.name ?? rule.activity_id} · ${rule.rule_type}${rule.is_archived ? " · ARCHIVED" : ""}`} /><div className="space-y-5 p-5">
      <form className="flex flex-wrap gap-2" onSubmit={(e) => { e.preventDefault(); const fd = new FormData(e.currentTarget); void mutate<ScoringRulePublic>(`rename-${rule.id}`, `/api/backend/admin/config/scoring-rules/${rule.id}`, "PATCH", { name: String(fd.get("name")) }, "Rule renamed."); }}><Input className="max-w-md" name="name" defaultValue={rule.name} disabled={rule.is_archived} /><Button variant="secondary" disabled={rule.is_archived || busy === `rename-${rule.id}`}>Save name</Button>{!rule.is_archived ? <Button type="button" variant="danger" onClick={() => { const why = window.prompt("Reason for archiving this rule?")?.trim(); if (why) void mutate<ScoringRulePublic>(`archive-${rule.id}`, `/api/backend/admin/config/scoring-rules/${rule.id}/archive`, "POST", { reason: why }, "Rule archived."); }}>Archive</Button> : null}</form>
      {reference && !rule.is_archived ? <form onSubmit={(e) => void saveVersion(e, rule, pending)} className="grid gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4 lg:grid-cols-[180px_140px_1fr]"><label className="text-sm font-medium">Effective week<Input name="effective_from_week" type="date" defaultValue={pending?.effective_from_week ?? ""} className="mt-1" /></label><label className="text-sm font-medium">Max score<Input name="max_score" type="number" min={0} required defaultValue={reference.max_score} className="mt-1" /></label><label className="text-sm font-medium lg:row-span-2">Configuration JSON<Textarea name="configuration" className="mt-1 min-h-48 font-mono text-xs" defaultValue={pretty(reference.configuration)} /></label><div className="lg:col-span-2"><Button disabled={busy === `version-${rule.id}`}>{pending ? `Update pending v${pending.version_number}` : "Create pending version"}</Button><p className="mt-2 text-xs text-slate-500">ACTIVE/ARCHIVED versions are immutable. Backend validates the executable configuration before accepting it.</p></div></form> : !reference && !rule.is_archived ? <form onSubmit={(e) => void saveVersion(e, rule, null)} className="grid gap-4 rounded-xl border p-4 lg:grid-cols-3"><Input name="effective_from_week" type="date" /><Input name="max_score" type="number" min={0} required placeholder="Max score" /><Textarea name="configuration" defaultValue="{}" className="font-mono" /><Button>Create first pending version</Button></form> : null}
      <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-slate-500"><tr><th className="py-2">Version</th><th>Effective</th><th>Status</th><th>Max</th><th>Created</th></tr></thead><tbody>{versions.map(v => <tr className="border-t" key={v.id}><td className="py-2 font-semibold">v{v.version_number}</td><td>{v.effective_from_week}</td><td>{v.status}</td><td>{v.max_score}</td><td>{new Date(v.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>
    </div></Card>; })}</div>
  </div>;
}
