"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { apiFetch } from "@/lib/api/client";
import type { ActivityPublic, StandardPeriod, StandardPublic, StandardVersionPublic } from "@/lib/api/types";
import { Button } from "@/components/ui/button";
import { Card, CardHeader } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { MutationFeedback } from "@/components/admin/mutation-feedback";

function pretty(value: Record<string, unknown>): string { return JSON.stringify(value, null, 2); }
function parseObject(text: string): Record<string, unknown> { const value: unknown = JSON.parse(text); if (!value || Array.isArray(value) || typeof value !== "object") throw new Error("Target definition must be a JSON object."); return value as Record<string, unknown>; }

export function StandardManager({ standards, activities, versionsByStandard }: { standards: StandardPublic[]; activities: ActivityPublic[]; versionsByStandard: Record<string, StandardVersionPublic[]> }) {
  const router = useRouter();
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null);
  async function mutate<T>(key: string, url: string, method: string, body: unknown, message: string) { setBusy(key); setError(null); setSuccess(null); try { await apiFetch<T>(url, { method, body: JSON.stringify(body) }); setSuccess(message); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Standard change failed."); } finally { setBusy(null); } }
  async function createStandard(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const fd = new FormData(e.currentTarget); await mutate<StandardPublic>("create-standard", "/api/backend/admin/config/standards", "POST", { activity_id: String(fd.get("activity_id")), name: String(fd.get("name")) }, "Standard created."); }
  async function saveVersion(e: FormEvent<HTMLFormElement>, standard: StandardPublic, pending: StandardVersionPublic | null) { e.preventDefault(); const fd = new FormData(e.currentTarget); try { const target_definition = parseObject(String(fd.get("target_definition") ?? "{}")); const body = { effective_from_week: String(fd.get("effective_from_week") ?? "") || null, period: String(fd.get("period")) as StandardPeriod, target_definition }; await mutate<StandardVersionPublic>(`version-${standard.id}`, pending ? `/api/backend/admin/config/standard-versions/${pending.id}` : `/api/backend/admin/config/standards/${standard.id}/versions`, pending ? "PATCH" : "POST", body, pending ? "Pending standard version updated." : "Pending standard version created."); } catch (e2) { setError(e2 instanceof Error ? e2.message : "Invalid standard JSON."); } }
  return <div className="space-y-6"><MutationFeedback error={error} success={success} />
    <Card><CardHeader title="Create standard" description="Standards are analytical targets and do not automatically grant extra marks." /><form onSubmit={createStandard} className="grid gap-4 p-5 md:grid-cols-2"><label className="text-sm font-medium">Activity<Select name="activity_id" required className="mt-1" defaultValue=""><option value="" disabled>Select activity</option>{activities.filter(a => !a.is_archived).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</Select></label><label className="text-sm font-medium">Standard name<Input name="name" required minLength={2} className="mt-1" /></label><div className="md:col-span-2"><Button disabled={busy === "create-standard"}>Create standard</Button></div></form></Card>
    <div className="space-y-5">{standards.map(standard => { const versions = versionsByStandard[standard.id] ?? []; const pending = versions.find(v => v.status === "PENDING") ?? null; const reference = pending ?? versions.find(v => v.status === "ACTIVE") ?? versions[0] ?? null; const activity = activities.find(a => a.id === standard.activity_id); return <Card key={standard.id}><CardHeader title={standard.name} description={`${activity?.name ?? standard.activity_id}${standard.is_archived ? " · ARCHIVED" : ""}`} /><div className="space-y-5 p-5">
      <form className="flex flex-wrap gap-2" onSubmit={(e) => { e.preventDefault(); const fd = new FormData(e.currentTarget); void mutate<StandardPublic>(`rename-${standard.id}`, `/api/backend/admin/config/standards/${standard.id}`, "PATCH", { name: String(fd.get("name")) }, "Standard renamed."); }}><Input className="max-w-md" name="name" defaultValue={standard.name} disabled={standard.is_archived} /><Button variant="secondary" disabled={standard.is_archived}>Save name</Button>{!standard.is_archived ? <Button type="button" variant="danger" onClick={() => { const why = window.prompt("Reason for archiving this standard?")?.trim(); if (why) void mutate<StandardPublic>(`archive-${standard.id}`, `/api/backend/admin/config/standards/${standard.id}/archive`, "POST", { reason: why }, "Standard archived."); }}>Archive</Button> : null}</form>
      {reference && !standard.is_archived ? <form onSubmit={(e) => void saveVersion(e, standard, pending)} className="grid gap-4 rounded-xl border border-slate-200 bg-slate-50 p-4 lg:grid-cols-[180px_180px_1fr]"><label className="text-sm font-medium">Effective week<Input name="effective_from_week" type="date" defaultValue={pending?.effective_from_week ?? ""} className="mt-1" /></label><label className="text-sm font-medium">Period<Select name="period" defaultValue={reference.period} className="mt-1"><option value="DAILY">DAILY</option><option value="WEEKLY">WEEKLY</option></Select></label><label className="text-sm font-medium lg:row-span-2">Target JSON<Textarea name="target_definition" className="mt-1 min-h-40 font-mono text-xs" defaultValue={pretty(reference.target_definition)} /></label><div className="lg:col-span-2"><Button disabled={busy === `version-${standard.id}`}>{pending ? `Update pending v${pending.version_number}` : "Create pending version"}</Button><p className="mt-2 text-xs text-slate-500">FastAPI validates executable target definitions; active history remains immutable.</p></div></form> : !reference && !standard.is_archived ? <form onSubmit={(e) => void saveVersion(e, standard, null)} className="grid gap-3 rounded-xl border p-4 lg:grid-cols-3"><Input name="effective_from_week" type="date" /><Select name="period"><option>DAILY</option><option>WEEKLY</option></Select><Textarea name="target_definition" defaultValue="{}" className="font-mono" /><Button>Create first pending version</Button></form> : null}
      <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-slate-500"><tr><th className="py-2">Version</th><th>Effective</th><th>Period</th><th>Status</th><th>Created</th></tr></thead><tbody>{versions.map(v => <tr className="border-t" key={v.id}><td className="py-2 font-semibold">v{v.version_number}</td><td>{v.effective_from_week}</td><td>{v.period}</td><td>{v.status}</td><td>{new Date(v.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>
    </div></Card>; })}</div>
  </div>;
}
